name: ui
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  gap: ^3.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  freezed: ^2.4.7
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  get_it: ^8.0.0
  injectable: ^2.3.5
  dio: ^5.4.1
  retrofit: ^4.1.0
  path_provider: ^2.1.2
  open_file: ^3.3.2
  pretty_dio_logger: ^1.3.1
  flutter_markdown: ^0.7.4
  url_launcher: ^6.2.5
  webview_flutter_web: ^0.2.2+4
  equatable: ^2.0.5
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.2
  injectable_generator: ^2.5.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.4.0


flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:

  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
